apiVersion: v2
name: cluster-autoscaler
description: A Helm chart for EKS Cluster Autoscaler
version: 0.1.0
appVersion: 1.0
sources:
  - https://github.com/felipemadeiros-Dock/poc-helm/
maintainers:
  - name: Felipe Madeiros
    email: felipe.madeiros@dock.tech
